package me.mehadi.retrofitlivedatamvvmrecyclerviewdatabinding.presentation.theme

import androidx.compose.ui.graphics.Color

// Light scheme — "knowledge blue" primary with a violet tertiary accent.
val md_primary_light = Color(0xFF1E3A8A)
val md_onPrimary_light = Color(0xFFFFFFFF)
val md_primaryContainer_light = Color(0xFFD6E2FF)
val md_onPrimaryContainer_light = Color(0xFF001A41)
val md_secondary_light = Color(0xFF3B5CA8)
val md_onSecondary_light = Color(0xFFFFFFFF)
val md_secondaryContainer_light = Color(0xFFDCE6FF)
val md_onSecondaryContainer_light = Color(0xFF001B3F)
val md_tertiary_light = Color(0xFF7C3AED)
val md_onTertiary_light = Color(0xFFFFFFFF)
val md_tertiaryContainer_light = Color(0xFFEDE0FF)
val md_onTertiaryContainer_light = Color(0xFF24005C)
val md_error_light = Color(0xFFDC2626)
val md_onError_light = Color(0xFFFFFFFF)
val md_errorContainer_light = Color(0xFFFFDAD6)
val md_onErrorContainer_light = Color(0xFF410002)
val md_background_light = Color(0xFFF8FAFC)
val md_onBackground_light = Color(0xFF1B1B1F)
val md_surface_light = Color(0xFFF8FAFC)
val md_onSurface_light = Color(0xFF1B1B1F)
val md_surfaceVariant_light = Color(0xFFE1E2EC)
val md_onSurfaceVariant_light = Color(0xFF44474F)
val md_outline_light = Color(0xFF74777F)
val md_outlineVariant_light = Color(0xFFC4C6D0)
val md_inverseSurface_light = Color(0xFF303034)
val md_inverseOnSurface_light = Color(0xFFF2F0F4)
val md_inversePrimary_light = Color(0xFFB0C6FF)

// Dark scheme — lighter tones of the same hues for legibility on dark surfaces.
val md_primary_dark = Color(0xFFB0C6FF)
val md_onPrimary_dark = Color(0xFF002C71)
val md_primaryContainer_dark = Color(0xFF163D8F)
val md_onPrimaryContainer_dark = Color(0xFFD6E2FF)
val md_secondary_dark = Color(0xFFA9C7FF)
val md_onSecondary_dark = Color(0xFF00315C)
val md_secondaryContainer_dark = Color(0xFF234A8A)
val md_onSecondaryContainer_dark = Color(0xFFD9E2FF)
val md_tertiary_dark = Color(0xFFD6BBFF)
val md_onTertiary_dark = Color(0xFF3D1372)
val md_tertiaryContainer_dark = Color(0xFF5A2FA0)
val md_onTertiaryContainer_dark = Color(0xFFEDDCFF)
val md_error_dark = Color(0xFFFFB4AB)
val md_onError_dark = Color(0xFF690005)
val md_errorContainer_dark = Color(0xFF93000A)
val md_onErrorContainer_dark = Color(0xFFFFDAD6)
val md_background_dark = Color(0xFF121318)
val md_onBackground_dark = Color(0xFFE3E2E6)
val md_surface_dark = Color(0xFF121318)
val md_onSurface_dark = Color(0xFFE3E2E6)
val md_surfaceVariant_dark = Color(0xFF44474F)
val md_onSurfaceVariant_dark = Color(0xFFC4C6D0)
val md_outline_dark = Color(0xFF8E9099)
val md_outlineVariant_dark = Color(0xFF44474F)
val md_inverseSurface_dark = Color(0xFFE3E2E6)
val md_inverseOnSurface_dark = Color(0xFF2F3036)
val md_inversePrimary_dark = Color(0xFF1E3A8A)
